#!/bin/bash
# Version 3

packageServiceType="Plasma/Applet"
kpackagetoolCmd="kpackagetool6"
if ! command -v "${kpackagetoolCmd}" >/dev/null 2>&1; then
	kpackagetoolCmd="kpackagetool5"
fi

# Eg: kpackagetool6 -t "Plasma/Applet" -r package
"${kpackagetoolCmd}" -t "${packageServiceType}" -r package
